############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Programs"
hasChildren = true

  [[main]]
  parent = "Programs"
  name = "Unity DMV"
  url = "unitydmv/"
  weight = 1

  [[main]]
  parent = "Programs"
  name = "Unity NC"
  url = "unitync/"
  weight = 2



# footer menu
[[footer]]
name = "About Us"
url = "about/"
weight = 1
