publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

backend:
  name: git-gateway
  branch: main
  
collections:
  - name: "post"
    label: "Posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "content/english"
    fields: # The fields each document in this collection have
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "publish_date", widget: "datetime"}
        - {label: "Intro Blurb", name: "intro_blurb", widget: "text"}
        - {label: "Backround Image", name: "bg_image", widget: "file", required: false}
        - {label: "file", name: "image", widget: "files", required: false}
        - {label: "body", name: "body", widget: "markdown"}
        - {label: "tags", name: "tags", widget: "list", default: ["post"]}
        - {label: "author", name: "author", widget: "string"}
        - {label: "description", name: "description", widget: "string"}
        - {label: "catagories", name: "catagories", widget: "list"} 
 
 

